apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cipipelines.ci.example.com
spec:
  group: ci.example.com
  scope: Namespaced
  names:
    plural: cipipelines
    singular: cipipeline
    kind: CIPipeline
    shortNames:
      - cp
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema: {}
