openapi: 3.0.0
info:
  title: CIPipeline API
  description: API specification for managing CI Pipelines
  version: 1.0.0
components:
  schemas:
    CodeReview:
      type: object
      description: "Configuration for code review processes."
      properties:
        codeReviewerType:
          type: string
          enum: ["human", "llm"]
          description: "Type of code reviewer, either a human or an LLM tool."
        codeReviewer:
          type: string
          description: "Name of the tool if LLM was specified, or the email of the human reviewer if human was selected."
      additionalProperties: false

    Linter:
      type: object
      description: "Configuration for linting processes."
      properties:
        name:
          type: string
          enum: ["eslint", "pylint", "flake8", "rubocop", "golangci-lint", "stylelint", "checkstyle", "phpcs", "jshint", "tslint", "clang-tidy", "cppcheck", "mypy", "bandit", "shellcheck", "hadolint", "ktlint", "detekt", "sonarlint", "prettier"]
          description: "Name of the linter tool."
        configPath:
          type: string
          description: "Path to the configuration file for the linter."
        globPatterns:
          type: array
          items:
            type: string
          description: "Glob patterns to specify which files should be linted."
      additionalProperties: false

    SecretScan:
      type: object
      description: "Configuration for static code secret scanning tools."
      properties:
        toolName:
          type: string
          enum: ["gitleaks", "trufflehog", "detect-secrets", "git-secrets", "secretscanner", "whispers", "shhgit", "repo-supervisor", "yelp-detect-secrets", "bandit", "credstash", "aws-secrets-manager", "gitrob", "dops-secrets-scanner", "vault", "blackduck", "sonarqube", "checkov", "semgrep", "codescan"]
          description: "Name of the secret scanning tool."
        globPatterns:
          type: array
          items:
            type: string
          description: "Glob patterns to specify which files should be scanned."
        configPath:
          type: string
          description: "Path to the configuration file for the secret scanning tool."
      additionalProperties: false

    CustomStep:
      type: object
      description: "Configuration for a custom execution step."
      properties:
        command:
          type: string
          description: "Shell command to run."
        shell:
          type: string
          enum: ["sh", "bash", "zsh"]
          description: "Shell type to use (optional)."
        containerImage:
          type: string
          description: "Container image to use for execution."
        successCriteria:
          type: object
          description: "Criteria to determine if the command was successful."
          properties:
            statusCode:
              type: integer
              description: "Expected status code for success."
            outputRegex:
              type: string
              description: "Regex pattern that should be found in the output for success."
          additionalProperties: false
      required:
        - command
        - containerImage
      additionalProperties: false

    Repository:
      type: object
      description: "Configuration for securely accessing a Git repository."
      properties:
        url:
          type: string
          description: "URL of the Git repository."
        branch:
          type: string
          description: "Branch to check out."
        credentialsSource:
          type: string
          enum: ["hashicorp-vault", "external-secret-manager", "kubernetes-secret"]
          description: "Source of the credentials for accessing the repository."
        credentialsRef:
          type: object
          description: "Reference to the credentials stored in the specified source."
          properties:
            name:
              type: string
              description: "Name of the secret or credential reference."
            key:
              type: string
              description: "Key in the secret storing the credentials."
          additionalProperties: false
      additionalProperties: false

    CIPipeline:
      type: object
      x-kubernetes-group-version-kind:
        - group: opsdash.dev
          version: v1alpha1
          kind: CIPipeline
      properties:
        apiVersion:
          type: string
          example: "opsdash.dev/v1alpha1"
        kind:
          type: string
          example: "CIPipeline"
        metadata:
          type: object
          x-kubernetes-preserve-unknown-fields: true
        spec:
          type: object
          properties:
            srcRepository:
              $ref: "#/components/schemas/Repository"
            ciSystem:
              type: string
              description: "The CI system to use (e.g., Jenkins, GitHub Actions, GitLab CI)."
              enum: ["jenkins", "github", "gitlab", "azure"]
            triggers:
              type: object
              description: "Event-based trigger configuration."
              properties:
                event:
                  type: string
                  description: "Event type that triggers the pipeline (e.g., push, pull_request)."
                branch:
                  type: string
                  description: "Branch name filter for triggering the pipeline."
              additionalProperties: false
            preBuildSteps:
              type: array
              description: "List of pre-build validations and checks."
              items:
                oneOf:
                  - $ref: "#/components/schemas/Linter"
                  - $ref: "#/components/schemas/CodeReview"
                  - $ref: "#/components/schemas/CustomStep"
                  - $ref: "#/components/schemas/SecretScan"
            ociBuild:
              type: object
              description: >
                Settings for building the container image.
                Note: If taggingStrategy is 'custom', then customTag should be provided.
                This conditional requirement must be enforced by a validating admission webhook.
              properties:
                dockerfile:
                  type: string
                  description: "Path to the Dockerfile."
                context:
                  type: string
                  description: "Directory context for the build."
                taggingStrategy:
                  type: string
                  enum: ["git-commit", "semver", "custom"]
                  description: "Strategy for tagging the built image."
                customTag:
                  type: string
                  description: "Custom tag value. Should be provided when taggingStrategy is 'custom'."
              required:
                - dockerfile
                - context
                - taggingStrategy
              additionalProperties: false
            ociRegistry:
              type: object
              description: "Container registry configuration."
              properties:
                url:
                  type: string
                  description: "Registry URL."
                repository:
                  type: string
                  description: "Repository name in the registry."
                credentialsSource:
                  type: string
                  enum: ["hashicorp-vault", "external-secret-manager", "kubernetes-secret"]
                  description: "Source of the credentials for accessing the repository."
                credentialsRef:
                  type: object
                  description: "Reference to a Kubernetes Secret or external secret for registry credentials."
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                  additionalProperties: false
              additionalProperties: false
            notifications:
              type: object
              description: "Notification configuration for pipeline events."
              properties:
                webhook:
                  type: string
                  description: "Webhook URL for notifications."
                email:
                  type: string
                  description: "Email address for notifications."
              additionalProperties: false
          required:
            - srcRepository
            - ciSystem
            - ociBuild
            - ociRegistry
          additionalProperties: false
      additionalProperties: false
