apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cipipeline-validating-webhook
webhooks:
  - name: validating-webhook.opsdash.dev
    clientConfig:
      service:
        name: validating-webhook-service
        namespace: default
        path: "/validate"
      caBundle: <base64-encoded-ca-cert>
    rules:
      - apiGroups:
          - opsdash.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cipipelines
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
